project_name: "ConditionHOI_cgrasp"
# dataset settings
dataset: {
  name: obman,

  train: {_base_: ./cfgs/dataset_cfgs/obman_mae.yaml,
          others: {subset: 'train'}},
  val: {_base_: ./cfgs/dataset_cfgs/obman_mae.yaml,
        others: {subset: 'val'}},
  test: {_base_: ./cfgs/dataset_cfgs/obman_mae.yaml,
        others: {subset: 'test'}}}

# training settings
batch_size: 32
num_epoch: 60
early_stopping: 100
use_cuda: True
optimizer : {
  type: Adam,
  pretrain_lr: 1e-4,
  kwargs : {
    lr: 1e-4
    }
}

# model settings

model: {
    cnet_type: mae,
    cnet: {
      chkpt_path: '/ssd_data/yilin/Outputs/ConditionHOI/pretrain_comp_d3_2loss/models/checkpoint_50.pth',
      kwargs: {
        group_size: 32,
        num_group: 128,
        transformer: {
          mask_ratio: 0.6,
          mask_type: 'rand',
          trans_dim: 384,
          encoder_dims: 384,
          depth: 12,
          num_heads: 6,
          drop_path_rate: 0.1,
        }
      }
    },
    vae: {
      kwargs: {
        encoder_sizes: [1024, 512, 256],
        latent_size: 64,
        condition_size: 1024
      } 
    }
      
}
std_type: 'softplus'

# loss settings

coef: {
  kl_coef: 0.005,
  lambda_edge: 30.,
  lambda_mesh_rec_w:  30.,
  lambda_dist_h:  35.,
  lambda_dist_o:  35.,
}

hoi_hparams: {
  th_penet: -0.005,
  th_contact: 0.005,
  weight_contact: .1,
  weight_penet: 1.5,
  weight_region: 1.5,
}
vpe_path: "./cfgs/verts_per_edge.npy"
c_weights_path: "./cfgs/rhand_weight.npy"



# checkpoint / visual / 
check_interval: 1
visual_interval: {
  train:{
    batch: 500,
    sample: null
  },
  val: {
    batch: 10,
    sample: null
  }
}


# eval_inference_iteration
eval_iter: 5

# test settings 
test_part: False
test_select_k: 0.25
testmetrics: False
metrics_select : {
  contact: True,
  inter: True,
  simul: False,
  cond: True
}
voxel : {
  mode: voxels_hand,
  pitch: 0.01
}
threshold : {
  penetrate: -0.005,
  cond_dist: -0.005, #CHECK
  coverage: 0.6
}




