project_name: "ConditionHOI_pretrain"
# dataset settings
dataset: {
  name: obman_pretrain,

  train: {_base_: ./cfgs/dataset_cfgs/obman_pretrain_comp.yaml,
          others: {subset: 'train'}},
  val: {_base_: ./cfgs/dataset_cfgs/obman_pretrain_comp.yaml,
        others: {subset: 'val'}},
  test: {_base_: ./cfgs/dataset_cfgs/obman_pretrain_comp.yaml,
        others: {subset: 'test'}}}

# training settings
batch_size: 32
num_epoch: 200
early_stopping: 5
optimizer : {
  type: AdamW,
  kwargs : {
    lr: 5e-4,
    weight_decay: 5e-4,
    }
}

scheduler: {
  type: LambdaLR,
  kwargs : {
    decay_step: 21,
    lr_decay: 0.76,
    lowest_decay: 0.02,
    }
}

bnmscheduler: {
  type: Lambda,
  kwargs: {
    decay_step: 21,
    bn_decay: 0.5,
    bn_momentum: 0.9,
    lowest_decay: 0.01
  }
}

# model settings
model: {
  type: 'trans',
  kwargs: {
    embed_dim: 384,
    num_heads: 6,
    mlp_ratio: 2.,
    glob_feat_dim: 1024,
    depth: {
      encoder: 3, 
      decoder: 4},
    knn_k: 8,
    knn_layer_num: 1,
    num_query: 96,
    num_pred: 6144,
    fps: True
  }
}



# checkpoint / visual / 
check_interval: 2
visual_interval: {
  train:{
    batch: 500,
    sample: null
  },
  val: {
    batch: 10,
    sample: null
  }
}


# eval_inference_iteration
eval_iter: 5



