project_name: "ConditionHOI_pretrain"
# dataset settings
dataset: {
  name: obman_pretrain,

  train: {_base_: ./cfgs/dataset_cfgs/obman_pretrain_mae.yaml,
          others: {subset: 'train'}},
  val: {_base_: ./cfgs/dataset_cfgs/obman_pretrain_mae.yaml,
        others: {subset: 'val'}},
  test: {_base_: ./cfgs/dataset_cfgs/obman_pretrain_mae.yaml,
        others: {subset: 'test'}}}

# training settings
batch_size: 32
num_epoch: 300
early_stopping: 5

optimizer : {
  type: AdamW,
  kwargs: {
  lr : 0.001,
  weight_decay : 0.05
}}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 300,
    initial_epochs : 10
}}

# model settings
model: {
  group_size: 32,
  num_group: 128,
  transformer: {
    mask_ratio: 0.6,
    mask_type: 'rand',
    trans_dim: 384,
    encoder_dims: 384,
    depth: 12,
    num_heads: 6,
    drop_path_rate: 0.1,
    decoder_depth: 4,
    decoder_num_heads: 6,
  }
}



# checkpoint / visual / 
check_interval: 5
visual_interval: {
  train:{
    batch: 500,
    sample: null
  },
  val: {
    batch: 10,
    sample: null
  }
}


# eval_inference_iteration
eval_iter: 5



